definitions:
  models.AuthLogin:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.Member:
    properties:
      created_at:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      role_id:
        type: string
      updated_at:
        type: string
    type: object
  models.Response:
    properties:
      body: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  models.TenantCreate:
    properties:
      address:
        type: string
      cuit:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    required:
    - address
    - cuit
    - email
    - name
    - phone
    type: object
  models.TenantResponse:
    properties:
      address:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      phone:
        type: string
      updated_at:
        type: string
      user_is_active:
        type: boolean
    type: object
  models.TenantUserCreate:
    properties:
      tenant_create:
        $ref: '#/definitions/models.TenantCreate'
      user_create:
        $ref: '#/definitions/models.UserCreate'
    required:
    - tenant_create
    - user_create
    type: object
  models.UserCreate:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    - username
    type: object
info:
  contact: {}
  description: This is a api to app gestioncar
  termsOfService: http://swagger.io/terms/
  title: APP GESTIONCAR
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user required identifier and password
      parameters:
      - description: Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.AuthLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Login user
      tags:
      - Auth
  /auth/tenant_login/{tenant_id}:
    get:
      consumes:
      - application/json
      description: Login tenant required tenant_id
      parameters:
      - description: tenant_id
        in: path
        name: tenant_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: Login Tenant
      tags:
      - Auth
  /member/get_all:
    get:
      consumes:
      - application/json
      description: Memeber GetAll required auth token
      produces:
      - application/json
      responses:
        "200":
          description: Members obtenidos con éxito
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                body:
                  items:
                    $ref: '#/definitions/models.Member'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "401":
          description: Auth is required
          schema:
            $ref: '#/definitions/models.Response'
        "403":
          description: Not Authorized
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: Memeber GetAll
      tags:
      - Tenant
  /tenant/create:
    post:
      consumes:
      - application/json
      description: Tenant Create required auth token
      parameters:
      - description: TenantUserCreate
        in: body
        name: TenantUserCreate
        required: true
        schema:
          $ref: '#/definitions/models.TenantUserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Tenant creado con éxito
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "401":
          description: Auth is required
          schema:
            $ref: '#/definitions/models.Response'
        "403":
          description: Not Authorized
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: Tenant Create
      tags:
      - Tenant
  /tenant/get_all:
    get:
      consumes:
      - application/json
      description: Tenant GetAll required auth token
      produces:
      - application/json
      responses:
        "200":
          description: Workplaces obtenidos con éxito
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                body:
                  items:
                    $ref: '#/definitions/models.TenantResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "401":
          description: Auth is required
          schema:
            $ref: '#/definitions/models.Response'
        "403":
          description: Not Authorized
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: Tenant GetAll
      tags:
      - Tenant
  /user/create:
    post:
      consumes:
      - application/json
      description: Creates a new user.
      parameters:
      - description: User information
        in: body
        name: userCreate
        required: true
        schema:
          $ref: '#/definitions/models.UserCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "401":
          description: Auth is required
          schema:
            $ref: '#/definitions/models.Response'
        "403":
          description: Not Authorized
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: Create User
      tags:
      - User
securityDefinitions:
  BearerAuth:
    description: 'Type "Bearer" followed by a space and the JWT token. Example: "Bearer
      eyJhbGciOiJIUz..."'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
